# Generated by Django 5.2.7 on 2025-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App33', '0003_role_create_level_role_delete_level_role_read_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='token',
            field=models.CharField(default='default_token', max_length=64),
        ),
        migrations.AddField(
            model_name='access',
            name='token_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
